name: Builds

on: [push, pull_request]

jobs:
  Windows:
    name: Windows latest
    runs-on: windows-latest 
    strategy:
      fail-fast: false
      matrix:
        platform: ['x86', 'x64']
        configuration: ['Debug', 'Release']
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup vs prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      run: msbuild /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} src\symbolizer.sln

    - name: Copy dbghelp/symsrv x64
      if: ${{ matrix.platform == 'x64' }}
      run: |
        copy "c:\program Files (x86)\windows kits\10\debuggers\${{ matrix.platform }}\dbghelp.dll" src/x64/${{ matrix.configuration }}
        copy "c:\program Files (x86)\windows kits\10\debuggers\${{ matrix.platform }}\symsrv.dll" src/x64/${{ matrix.configuration }}
        copy "c:\program Files (x86)\windows kits\10\debuggers\${{ matrix.platform }}\dbgeng.dll" src/x64/${{ matrix.configuration }}
        copy "c:\program Files (x86)\windows kits\10\debuggers\${{ matrix.platform }}\dbgcore.dll" src/x64/${{ matrix.configuration }}

    - name: Copy dbghelp/symsrv x86
      if: ${{ matrix.platform == 'x86' }}
      run: |
        copy "c:\program Files (x86)\windows kits\10\debuggers\${{ matrix.platform }}\dbghelp.dll" src/${{ matrix.configuration }}
        copy "c:\program Files (x86)\windows kits\10\debuggers\${{ matrix.platform }}\symsrv.dll" src/${{ matrix.configuration }}
        copy "c:\program Files (x86)\windows kits\10\debuggers\${{ matrix.platform }}\dbgeng.dll" src/${{ matrix.configuration }}
        copy "c:\program Files (x86)\windows kits\10\debuggers\${{ matrix.platform }}\dbgcore.dll" src/${{ matrix.configuration }}


    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: bin-${{ matrix.platform }}.${{matrix.configuration }}
        path: |
          src/**/${{ matrix.configuration }}/symbolizer.exe
          src/**/${{ matrix.configuration }}/symbolizer.pdb
          src/**/${{ matrix.configuration }}/dbghelp.dll
          src/**/${{ matrix.configuration }}/symsrv.dll
          src/**/${{ matrix.configuration }}/dbgeng.dll
          src/**/${{ matrix.configuration }}/dbgcore.dll